### ISSUE TITLE
Creating new Domain Records - ApiException: Not Found

### ISSUE THREAD

**Issue by BaronVonPerko** [trmcnvn/DigitalOcean.API#32]
Unable to create domain records and am getting the Not Found exception.  Is this a bug or am I doing something wrong?

Thanks!

```csharp
// subdomainName and ip are passed into this method

var record = new DomainRecord()
{
    Type = "A",
    Name = subdomainName,
    Data = ip,
};

await _client.DomainRecords.Create($"{subdomainName}", record);
```

```
Unhandled Exception: DigitalOcean.API.Exceptions.ApiException: Not Found
   at DigitalOcean.API.Extensions.RestSharpExtensions.ThrowIfException(IRestResponse response)
   at DigitalOcean.API.Extensions.RestSharpExtensions.ExecuteTask[T](IRestClient client, IRestRequest request)
   at DigitalOcean.API.Http.Connection.ExecuteRequest[T](String endpoint, IList`1 parameters, Object data, String expectedRoot, Method method)
   at ServerManager.Services.DigitalOceanService.AddDnsRecord(String ip, String subdomainName, String domainName) in C:\Users\chris\code\codestage\ServerManager\Services\DigitalOceanService.cs:line 83
   at CodeStageConsole.Commands.CreateWordpressSiteCommand.Execute(IService serverManager, Int32 serverId, String siteName) in C:\Users\chris\code\codestage\CodeStageConsole\Commands\CreateWordpressSiteCommand.cs:line 24
   at CodeStageConsole.Program.OnExecute() in C:\Users\chris\code\codestage\CodeStageConsole\Program.cs:line 65
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)
   at CodeStageConsole.Program.Main(String[] args) in C:\Users\chris\code\codestage\CodeStageConsole\Program.cs:line 32
```

**Comment by BaronVonPerko** [comment]
Of course, right after I put this issue together, I solved it.  In case anyone else runs into this:

The first parameter of the DomainRecords.Create() corresponds to the domain name that the new networking record will reside under.

Example: if I am trying to create a subdomain for "mysite.com" which will be called "sub.mysite.com", then we need to do:

```csharp
await _client.DomainRecords.Create("mysite.com", record)
```
